### ISSUE TITLE
Error while creating an event in CiviCRM

### ISSUE THREAD

**Issue by kurund** [christianwach/civicrm-event-organiser#30]
Create an event in CiviCRM by entering required fields and it throws below error.

 **Sorry, due to an error, we are unable to fulfill your request at the moment. You may want to contact your administrator or service provider with more details about what action you were performing when this occurred.
DateTime::__construct(): Failed to parse time string (null) at position 0 (n): The timezone could not be found in the database
Return to home page.**

Below is the backtrace.

```
Feb 02 19:04:09  [error] 
$Fatal Error Details = array:3 [
  "message" => "DateTime::__construct(): Failed to parse time string (null) at position 0 (n): The timezone could not be found in the database"
  "code" => null
  "exception" => Exception {#9274
    #message: "DateTime::__construct(): Failed to parse time string (null) at position 0 (n): The timezone could not be found in the database"
    #code: 0
    #file: "/var/www/html/wp-content/plugins/civicrm-event-organiser/includes/civicrm-event-organiser-eo.php"
    #line: 439
    +"severity": 2
    trace: {
      /var/www/html/wp-content/plugins/civicrm-event-organiser/includes/civicrm-event-organiser-eo.php:439 {
        <E2><80><BA> // End date and end of schedule are the same.
        <E2><80><BA> 'end' => new DateTime( $civi_event['end_date'], eo_get_blog_timezone() ),
        <E2><80><BA> 'schedule_last' => new DateTime( $civi_event['end_date'], eo_get_blog_timezone() ),
        arguments: {
          $time: "null"
          $timezone: DateTimeZone {#9269 <E2><80><A6>}
        }
      }
      /var/www/html/wp-content/plugins/civicrm-event-organiser/includes/civicrm-event-organiser-civi.php:208 { <E2><80><A6>}
      /var/www/html/wp-includes/class-wp-hook.php:287 { <E2><80><A6>}
      /var/www/html/wp-includes/class-wp-hook.php:311 { <E2><80><A6>}
      /var/www/html/wp-includes/plugin.php:551 { <E2><80><A6>}
      /var/www/html/wp-content/plugins/civicrm/civicrm/CRM/Utils/Hook/WordPress.php:108 { <E2><80><A6>}
      /var/www/html/wp-content/plugins/civicrm/civicrm/Civi/Core/CiviEventDispatcher.php:180 { <E2><80><A6>}
      /var/www/html/wp-content/plugins/civicrm/civicrm/vendor/symfony/event-dispatcher/EventDispatcher.php:214 { <E2><80><A6>}
      /var/www/html/wp-content/plugins/civicrm/civicrm/vendor/symfony/event-dispatcher/EventDispatcher.php:44 { <E2><80><A6>}
      /var/www/html/wp-content/plugins/civicrm/civicrm/Civi/Core/CiviEventDispatcher.php:129 { <E2><80><A6>}
      /var/www/html/wp-content/plugins/civicrm/civicrm/CRM/Utils/Hook.php:366 { <E2><80><A6>}
      /var/www/html/wp-content/plugins/civicrm/civicrm/CRM/Event/BAO/Event.php:90 { <E2><80><A6>}
      /var/www/html/wp-content/plugins/civicrm/civicrm/CRM/Event/BAO/Event.php:128 { <E2><80><A6>}
      /var/www/html/wp-content/plugins/civicrm/civicrm/CRM/Event/Form/ManageEvent/EventInfo.php:250 { <E2><80><A6>}
      /var/www/html/wp-content/plugins/civicrm/civicrm/CRM/Core/Form.php:514 { <E2><80><A6>}
      /var/www/html/wp-content/plugins/civicrm/civicrm/CRM/Core/QuickForm/Action/Upload.php:152 { <E2><80><A6>}
      /var/www/html/wp-content/plugins/civicrm/civicrm/CRM/Core/QuickForm/Action/Upload.php:119 { <E2><80><A6>}
      /var/www/html/wp-content/plugins/civicrm/civicrm/packages/HTML/QuickForm/Controller.php:203 { <E2><80><A6>}
      /var/www/html/wp-content/plugins/civicrm/civicrm/packages/HTML/QuickForm/Page.php:103 { <E2><80><A6>}
      /var/www/html/wp-content/plugins/civicrm/civicrm/CRM/Core/Controller.php:347 { <E2><80><A6>}
      /var/www/html/wp-content/plugins/civicrm/civicrm/CRM/Utils/Wrapper.php:98 { <E2><80><A6>}
      /var/www/html/wp-content/plugins/civicrm/civicrm/CRM/Core/Invoke.php:285 { <E2><80><A6>}
      /var/www/html/wp-content/plugins/civicrm/civicrm/CRM/Core/Invoke.php:68 { <E2><80><A6>}
      /var/www/html/wp-content/plugins/civicrm/civicrm/CRM/Core/Invoke.php:36 { <E2><80><A6>}
      /var/www/html/wp-content/plugins/civicrm/civicrm.php:1649 { <E2><80><A6>}
      /var/www/html/wp-includes/class-wp-hook.php:287 { <E2><80><A6>}
      /var/www/html/wp-includes/class-wp-hook.php:311 { <E2><80><A6>}
      /var/www/html/wp-includes/plugin.php:484 { <E2><80><A6>}
      /var/www/html/wp-admin/admin.php:259 { <E2><80><A6>}
    }
  }
]


Feb 02 19:04:09  [debug] $backTrace = #0 /var/www/html/wp-content/plugins/civicrm/civicrm/CRM/Core/Error.php(433): CRM_Core_Error::backtrace("backTrace", TRUE)
#1 /var/www/html/wp-content/plugins/civicrm/civicrm/CRM/Core/Invoke.php(39): CRM_Core_Error::handleUnhandledException(Object(Exception))
#2 /var/www/html/wp-content/plugins/civicrm/civicrm.php(1649): CRM_Core_Invoke::invoke((Array:3))
#3 /var/www/html/wp-includes/class-wp-hook.php(287): CiviCRM_For_WordPress->invoke("")
#4 /var/www/html/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters("", (Array:1))
#5 /var/www/html/wp-includes/plugin.php(484): WP_Hook->do_action((Array:1))
#6 /var/www/html/wp-admin/admin.php(259): do_action("toplevel_page_CiviCRM")
#7 {main}

```

Note that timezone is selected in WordPress. It is UTC+0

**Comment by christianwach** [comment]
@kurund I think "The timezone could not be found in the database" is the relevant part. I suspect WordPress shows "UTC+0" in the UI when there's no stored value. Try setting a proper timezone and see if the error persists.

**Comment by kurund** [comment]
@christianwach Actually I re-saved the timezone and checked too. Same issue persist.

**Comment by christianwach** [comment]
@kurund Did you stick with UTC+0? Can you verify that there's a value stored in the DB?

`get_option( 'timezone_string' )`

**Comment by kurund** [comment]
@christianwach Sorry for the delayed response.

`get_option( 'timezone_string' )`

I have empty value for this.

It is going in below condition

```
if (empty($tzstring)) {
	$tzstring = 'UTC';
}
```

**Comment by christianwach** [comment]
> I have empty value for this.

@kurund May I suggest you simply set a value? Or is there a specific reason you don't want to?

**Comment by kurund** [comment]
@christianwach wouldn't this get set if update 'General Settings' ?

**Comment by kurund** [comment]
I event selected timezone city 'London' and still get the same error.

**Comment by christianwach** [comment]
@kurund Sorry, I'm unable to reproduce this on any dev or client install. You're going to have to debug your install to find out why `eo_get_blog_timezone()` is returning `null`.

**Comment by kurund** [comment]
@christianwach problem seems to be creating date when the end_date = null. I have submitted the PR for this fix.
